name: handoff_vdb_2025
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/mobx
  mobx:
  # https://pub.dev/packages/flutter_mobx
  flutter_mobx: ^2.3.0
  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3
  # https://pub.dev/documentation/scroll_to_index/latest/
  scroll_to_index: any
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.2.0
  # https://pub.dev/packages/dio
  dio: ^5.8.0+1
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.3
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/flashy_flushbar
  flashy_flushbar: ^1.4.0
  # https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # https://pub.dev/packages/video_player
  video_player: ^2.10.0
  # https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: ^3.2.0
  # https://pub.dev/packages/cookie_jar
  cookie_jar: ^4.0.8
  # Camera. https://pub.dev/packages/camera
  camera: 0.10.5
  # https://pub.dev/packages/app_tracking_transparency
  carousel_slider: ^4.0.0
  # https://pub.dev/packages/image_picker
  image_picker: ^1.1.2
  #https://pub.dev/packages/image_cropper
  image_cropper: ^9.1.0
  # https://pub.dev/packages/http_parser
  http_parser: ^4.1.2
  # https://pub.dev/packages/cached_network_image/example
  cached_network_image: ^3.4.1
  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/file_picker
  file_picker: 10.2.1
  # https://pub.dev/packages/path
  path: ^1.9.1
  # https://pub.dev/packages/image
  image: ^4.5.4
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.2
  # https://pub.dev/packages/mime
  mime: ^2.0.0
  # https://pub.dev/packages/http
  http: ^1.5.0
  # https://pub.dev/packages/lottie
  lottie: ^3.3.1
  # https://pub.dev/packages/receive_sharing_intent
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
  # https://pub.dev/packages/flutter_mentions/versions
  flutter_mentions: ^2.0.1
  # https://pub.dev/packages/comment_tree/versions
  comment_tree:
    git:  https://github.com/DoanHieu1308/comment_tree.git
  # https://pub.dev/packages/youtube_player_flutter
  youtube_player_flutter: ^9.1.2
  # https://pub.dev/packages/visibility_detector/versions
  visibility_detector: ^0.4.0+2
  # https://pub.dev/packages/webview_flutter
  webview_flutter: ^4.13.0
  # https://pub.dev/packages/hive/versions
  hive: ^2.2.3
  # https://pub.dev/packages/hive_flutter
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.1.5
  # https://pub.dev/packages/chatview/example
  chatview: ^2.5.0
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^6.0.0
  # https://pub.dev/packages/firebase_core
  firebase_core: ^4.0.0
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^6.0.1
  # https://pub.dev/packages/firebase_database
  firebase_database: ^12.0.0
  # https://pub.dev/packages/flutter_slidable
  flutter_slidable: ^4.0.1
  # https://pub.dev/packages/vibration
  vibration: ^3.1.3
  # https://pub.dev/packages/device_info_plus
  device_info_plus: any
  # https://pub.dev/packages/photo_manager
  photo_manager: ^3.7.1
  # https://pub.dev/packages/image_network
  image_network: ^2.6.0
  # https://pub.dev/packages/flutter_widget_from_html
  flutter_widget_from_html: 0.16.1
  # https://pub.dev/packages/share_plus
  share_plus: ^12.0.0
  # https://pub.dev/packages/draggable_fab
  draggable_fab: ^0.1.4
  # https://pub.dev/packages/app_links/example
  app_links: ^6.4.1
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^19.4.2
  # https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^16.0.1
  # https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^6.0.0

  go_router: ^16.0.0

  cupertino_icons: ^1.0.8
  flutter_keyboard_visibility: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner:
  # https://pub.dev/packages/mobx_codegen
  mobx_codegen:
  # https://pub.dev/packages/hive_generator/versions
  hive_generator: ^2.0.1


  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/base/
    - assets/features/
    - assets/base/icons/
    - assets/base/images/
    - assets/features/video1.mp4
    - .env

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/base/fonts/inter/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/base/fonts/inter/Inter-Medium.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/base/fonts/inter/Inter-Bold.ttf
    - family: Inter-ExtraBold
      fonts:
        - asset: assets/base/fonts/inter/Inter-ExtraBold.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/base/fonts/inter/Inter-SemiBold.ttf
