name: handoff_vdb_2025
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/mobx
  mobx:
  # https://pub.dev/packages/flutter_mobx
  flutter_mobx: ^2.3.0
  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3
  # https://pub.dev/documentation/scroll_to_index/latest/
  scroll_to_index: any
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.2.0
  # https://pub.dev/packages/dio
  dio: ^5.8.0+1
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.3
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/flashy_flushbar
  flashy_flushbar: ^1.4.0
  # https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # https://pub.dev/packages/video_player
  video_player: ^2.10.0
  # https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: ^3.2.0
  # https://pub.dev/packages/cookie_jar
  cookie_jar: ^4.0.8
  # Camera. https://pub.dev/packages/camera
  camera: 0.10.5
  # https://pub.dev/packages/app_tracking_transparency
  carousel_slider: ^4.0.0
  # https://pub.dev/packages/image_picker
  image_picker: ^1.1.2
  #https://pub.dev/packages/image_cropper
  image_cropper: ^9.1.0
  # https://pub.dev/packages/http_parser
  http_parser: ^4.1.2
  # https://pub.dev/packages/cached_network_image/example
  cached_network_image: ^3.4.1
  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/file_picker
  file_picker: 10.2.1
  # https://pub.dev/packages/path
  path: ^1.9.1
  # https://pub.dev/packages/image
  image: ^4.5.4
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.2
  # https://pub.dev/packages/mime
  mime: ^2.0.0
  # https://pub.dev/packages/http
  http: ^1.5.0
  # https://pub.dev/packages/lottie
  lottie: ^3.3.1
  # https://pub.dev/packages/receive_sharing_intent
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent

  go_router: ^16.0.0

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner:
  # https://pub.dev/packages/mobx_codegen
  mobx_codegen:


  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/base/
    - assets/features/
    - assets/base/icons/
    - assets/features/video1.mp4

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/base/fonts/inter/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/base/fonts/inter/Inter-Medium.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/base/fonts/inter/Inter-Bold.ttf
    - family: Inter-ExtraBold
      fonts:
        - asset: assets/base/fonts/inter/Inter-ExtraBold.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/base/fonts/inter/Inter-SemiBold.ttf
