// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmXRkXUrJe69VZj4bUs8KEtbeIW6voQ1g',
    appId: '1:1018382182517:android:09951ba7237abac2a6303c',
    messagingSenderId: '1018382182517',
    projectId: 'handoffvdb2025',
    storageBucket: 'handoffvdb2025.firebasestorage.app',
    databaseURL: 'https://handoffvdb2025-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMmU5eo_atqNOGfiMPkmtO99jHCExfmeo',
    appId: '1:1018382182517:ios:350487ec497cd404a6303c',
    messagingSenderId: '1018382182517',
    projectId: 'handoffvdb2025',
    storageBucket: 'handoffvdb2025.firebasestorage.app',
    iosBundleId: 'com.example.handoffVdb2025',
    databaseURL: 'https://handoffvdb2025-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmXRkXUrJe69VZj4bUs8KEtbeIW6voQ1g',
    appId: '1:1018382182517:web:09951ba7237abac2a6303c',
    messagingSenderId: '1018382182517',
    projectId: 'handoffvdb2025',
    authDomain: 'handoffvdb2025.firebaseapp.com',
    storageBucket: 'handoffvdb2025.firebasestorage.app',
    databaseURL: 'https://handoffvdb2025-default-rtdb.firebaseio.com',
  );
}
